
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.gunsmithcognitis.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.BlockItem;

import net.mcreator.gunsmithcognitis.item.WheellockgunkitItem;
import net.mcreator.gunsmithcognitis.item.WheellockSportingRifleItem;
import net.mcreator.gunsmithcognitis.item.WheellockPistolItem;
import net.mcreator.gunsmithcognitis.item.WheellockPetronelItem;
import net.mcreator.gunsmithcognitis.item.WheellockMusketItem;
import net.mcreator.gunsmithcognitis.item.WheellockKalthoffRepeaterItem;
import net.mcreator.gunsmithcognitis.item.WheellockCarbineItem;
import net.mcreator.gunsmithcognitis.item.WheellockBlueprintMasteryItem;
import net.mcreator.gunsmithcognitis.item.WheellockBlueprintItem;
import net.mcreator.gunsmithcognitis.item.WheellockBlueprintIntermediateItem;
import net.mcreator.gunsmithcognitis.item.UniversalBlueprintItem;
import net.mcreator.gunsmithcognitis.item.ThreeeyegunItem;
import net.mcreator.gunsmithcognitis.item.TanegashimaItem;
import net.mcreator.gunsmithcognitis.item.StonepikeItem;
import net.mcreator.gunsmithcognitis.item.StonehalberdItem;
import net.mcreator.gunsmithcognitis.item.SpringfieldModel1861RifledMusketItem;
import net.mcreator.gunsmithcognitis.item.SpringfieldModel1861RifledMusketBayonetItem;
import net.mcreator.gunsmithcognitis.item.SmoothborebarrelItem;
import net.mcreator.gunsmithcognitis.item.ShotgunShellItem;
import net.mcreator.gunsmithcognitis.item.SawnOffDoubleBarrelShotgunItem;
import net.mcreator.gunsmithcognitis.item.SawnOffColtRevolver1855Item;
import net.mcreator.gunsmithcognitis.item.SawnColtRevolvingShotgun1855Item;
import net.mcreator.gunsmithcognitis.item.RockItem;
import net.mcreator.gunsmithcognitis.item.RiflingtoolItem;
import net.mcreator.gunsmithcognitis.item.RifledbarrelItem;
import net.mcreator.gunsmithcognitis.item.RevolverDrumItem;
import net.mcreator.gunsmithcognitis.item.RamrodItem;
import net.mcreator.gunsmithcognitis.item.PorterTurretRifleItem;
import net.mcreator.gunsmithcognitis.item.PercussionnippleItem;
import net.mcreator.gunsmithcognitis.item.PercussioncapgunkitItem;
import net.mcreator.gunsmithcognitis.item.PercussioncapMechanismItem;
import net.mcreator.gunsmithcognitis.item.PercussioncapBlueprintMasteryItem;
import net.mcreator.gunsmithcognitis.item.PercussioncapBlueprintItem;
import net.mcreator.gunsmithcognitis.item.PercussioncapBlueprintIntermediateItem;
import net.mcreator.gunsmithcognitis.item.Pattern1851minierifleItem;
import net.mcreator.gunsmithcognitis.item.Pattern1851MinieRifleBayonetItem;
import net.mcreator.gunsmithcognitis.item.PaperCartidgeSmallAmmoItem;
import net.mcreator.gunsmithcognitis.item.PaperCartidgeAmmoItem;
import net.mcreator.gunsmithcognitis.item.NockVolleyGunItem;
import net.mcreator.gunsmithcognitis.item.NockVolleyGunFrontComponentItem;
import net.mcreator.gunsmithcognitis.item.NetheritehalberdItem;
import net.mcreator.gunsmithcognitis.item.NetheritePikeItem;
import net.mcreator.gunsmithcognitis.item.MusketballItem;
import net.mcreator.gunsmithcognitis.item.MusketBallProjectileItem;
import net.mcreator.gunsmithcognitis.item.MortarballItem;
import net.mcreator.gunsmithcognitis.item.MiquoletMusketItem;
import net.mcreator.gunsmithcognitis.item.MiniePaperCartidgeAmmoItem;
import net.mcreator.gunsmithcognitis.item.MinieBallItem;
import net.mcreator.gunsmithcognitis.item.MatchlockrepairItem;
import net.mcreator.gunsmithcognitis.item.MatchlockWallGunItem;
import net.mcreator.gunsmithcognitis.item.MatchlockSnaphanceMusketItem;
import net.mcreator.gunsmithcognitis.item.MatchlockPistolItem;
import net.mcreator.gunsmithcognitis.item.MatchlockHeavyArquebusItem;
import net.mcreator.gunsmithcognitis.item.MatchlockBlunderbussItem;
import net.mcreator.gunsmithcognitis.item.MatchlockBlueprintMasteryItem;
import net.mcreator.gunsmithcognitis.item.MatchlockBlueprintItem;
import net.mcreator.gunsmithcognitis.item.MatchlockBlueprintIntermediateItem;
import net.mcreator.gunsmithcognitis.item.MatchlockAxePistolItem;
import net.mcreator.gunsmithcognitis.item.MatchlockArquebusItem;
import net.mcreator.gunsmithcognitis.item.LorenzPistolItem;
import net.mcreator.gunsmithcognitis.item.LandsknechtHarkebusItem;
import net.mcreator.gunsmithcognitis.item.KentuckyPistolItem;
import net.mcreator.gunsmithcognitis.item.JosephEggPistolItem;
import net.mcreator.gunsmithcognitis.item.JezailmusketItem;
import net.mcreator.gunsmithcognitis.item.IronpikeItem;
import net.mcreator.gunsmithcognitis.item.IronhalberdItem;
import net.mcreator.gunsmithcognitis.item.HeavyMusketballItem;
import net.mcreator.gunsmithcognitis.item.HeavyMusketBallProjectileItem;
import net.mcreator.gunsmithcognitis.item.HandgunneItem;
import net.mcreator.gunsmithcognitis.item.HandcannonItem;
import net.mcreator.gunsmithcognitis.item.HandBombItem;
import net.mcreator.gunsmithcognitis.item.GoldpikeItem;
import net.mcreator.gunsmithcognitis.item.GoldhalberdItem;
import net.mcreator.gunsmithcognitis.item.Fusil1866ChassepotItem;
import net.mcreator.gunsmithcognitis.item.Fusil1866ChassepotBayonetItem;
import net.mcreator.gunsmithcognitis.item.FulminatepowderItem;
import net.mcreator.gunsmithcognitis.item.FlintlockmusketgoldItem;
import net.mcreator.gunsmithcognitis.item.FlintlockmusketbayonetItem;
import net.mcreator.gunsmithcognitis.item.FlintlockmusketItem;
import net.mcreator.gunsmithcognitis.item.FlintlockgunkitItem;
import net.mcreator.gunsmithcognitis.item.FlintlockRifledCarbineItem;
import net.mcreator.gunsmithcognitis.item.FlintlockPistolItem;
import net.mcreator.gunsmithcognitis.item.FlintlockPistolGoldItem;
import net.mcreator.gunsmithcognitis.item.FlintlockPepperboxItem;
import net.mcreator.gunsmithcognitis.item.FlintlockPepperboxCarbineItem;
import net.mcreator.gunsmithcognitis.item.FlintlockMechanismItem;
import net.mcreator.gunsmithcognitis.item.FlintlockLorenzoniRepeaterItem;
import net.mcreator.gunsmithcognitis.item.FlintlockHeavyDragoonPistolItem;
import net.mcreator.gunsmithcognitis.item.FlintlockHandMortarItem;
import net.mcreator.gunsmithcognitis.item.FlintlockDoubleBarrelPistolItem;
import net.mcreator.gunsmithcognitis.item.FlintlockDoubleBarrelMusketItem;
import net.mcreator.gunsmithcognitis.item.FlintlockCollierRevolvingCarbineItem;
import net.mcreator.gunsmithcognitis.item.FlintlockCollierRevolverItem;
import net.mcreator.gunsmithcognitis.item.FlintlockBlunderbussItem;
import net.mcreator.gunsmithcognitis.item.FlintlockBlueprintMasteryItem;
import net.mcreator.gunsmithcognitis.item.FlintlockBlueprintItem;
import net.mcreator.gunsmithcognitis.item.FlintlockBlueprintIntermediateItem;
import net.mcreator.gunsmithcognitis.item.FlintlockAsumetteRifledWallGunItem;
import net.mcreator.gunsmithcognitis.item.FergusonRifleItem;
import net.mcreator.gunsmithcognitis.item.Enfield1853MusketRifleItem;
import net.mcreator.gunsmithcognitis.item.DynamitePackItem;
import net.mcreator.gunsmithcognitis.item.DynamiteItem;
import net.mcreator.gunsmithcognitis.item.DreyseNeedleGunItem;
import net.mcreator.gunsmithcognitis.item.DoubleBarrelsPartItem;
import net.mcreator.gunsmithcognitis.item.DoubleBarrelShotgunItem;
import net.mcreator.gunsmithcognitis.item.DivineFiveThunderMachineItem;
import net.mcreator.gunsmithcognitis.item.DiamondhalberdItem;
import net.mcreator.gunsmithcognitis.item.DiamondPikeItem;
import net.mcreator.gunsmithcognitis.item.CuirassItem;
import net.mcreator.gunsmithcognitis.item.CrudeSmoothborebarrelItem;
import net.mcreator.gunsmithcognitis.item.CrudeBigborebarrelItem;
import net.mcreator.gunsmithcognitis.item.ColtWalker1847Item;
import net.mcreator.gunsmithcognitis.item.ColtRevolvingShotgun1855Item;
import net.mcreator.gunsmithcognitis.item.ColtRevolvingRifle1855Item;
import net.mcreator.gunsmithcognitis.item.ColtPeterson1836Item;
import net.mcreator.gunsmithcognitis.item.ColtDragoon1848Item;
import net.mcreator.gunsmithcognitis.item.ColtArmy1860Item;
import net.mcreator.gunsmithcognitis.item.ChassepotBayonetItem;
import net.mcreator.gunsmithcognitis.item.CavalrySabreItem;
import net.mcreator.gunsmithcognitis.item.BrowningHarmonicaRifleItem;
import net.mcreator.gunsmithcognitis.item.BrowningHarmonicaClipItem;
import net.mcreator.gunsmithcognitis.item.BoltMechanismItem;
import net.mcreator.gunsmithcognitis.item.BigborebarrelItem;
import net.mcreator.gunsmithcognitis.item.BigGame4BorePercussionRifleItem;
import net.mcreator.gunsmithcognitis.item.AdvancedRevolversBlueprintItem;
import net.mcreator.gunsmithcognitis.item.Adams1856RevolverItem;
import net.mcreator.gunsmithcognitis.GunsmithCognitisMod;

public class GunsmithCognitisModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, GunsmithCognitisMod.MODID);
	public static final RegistryObject<Item> MUSKETBALL = REGISTRY.register("musketball", () -> new MusketballItem());
	public static final RegistryObject<Item> MUSKET_BALL_PROJECTILE = REGISTRY.register("musket_ball_projectile", () -> new MusketBallProjectileItem());
	public static final RegistryObject<Item> PAPER_CARTIDGE_AMMO = REGISTRY.register("paper_cartidge_ammo", () -> new PaperCartidgeAmmoItem());
	public static final RegistryObject<Item> RAMROD = REGISTRY.register("ramrod", () -> new RamrodItem());
	public static final RegistryObject<Item> MATCHLOCKGUNKIT = REGISTRY.register("matchlockgunkit", () -> new MatchlockrepairItem());
	public static final RegistryObject<Item> FLINTLOCK_BLUEPRINT = REGISTRY.register("flintlock_blueprint", () -> new FlintlockBlueprintItem());
	public static final RegistryObject<Item> PAPER_CARTIDGE_SMALL_AMMO = REGISTRY.register("paper_cartidge_small_ammo", () -> new PaperCartidgeSmallAmmoItem());
	public static final RegistryObject<Item> FLINTLOCKGUNKIT = REGISTRY.register("flintlockgunkit", () -> new FlintlockgunkitItem());
	public static final RegistryObject<Item> WHEELLOCKGUNKIT = REGISTRY.register("wheellockgunkit", () -> new WheellockgunkitItem());
	public static final RegistryObject<Item> RIFLEDBARREL = REGISTRY.register("rifledbarrel", () -> new RifledbarrelItem());
	public static final RegistryObject<Item> RIFLINGTOOL = REGISTRY.register("riflingtool", () -> new RiflingtoolItem());
	public static final RegistryObject<Item> SMOOTHBOREBARREL = REGISTRY.register("smoothborebarrel", () -> new SmoothborebarrelItem());
	public static final RegistryObject<Item> CRUDE_SMOOTHBOREBARREL = REGISTRY.register("crude_smoothborebarrel", () -> new CrudeSmoothborebarrelItem());
	public static final RegistryObject<Item> NOCK_VOLLEY_GUN_FRONT_COMPONENT = REGISTRY.register("nock_volley_gun_front_component", () -> new NockVolleyGunFrontComponentItem());
	public static final RegistryObject<Item> MORTARBALL = REGISTRY.register("mortarball", () -> new MortarballItem());
	public static final RegistryObject<Item> REVOLVER_DRUM = REGISTRY.register("revolver_drum", () -> new RevolverDrumItem());
	public static final RegistryObject<Item> CAVALRY_SABRE = REGISTRY.register("cavalry_sabre", () -> new CavalrySabreItem());
	public static final RegistryObject<Item> STONEPIKE = REGISTRY.register("stonepike", () -> new StonepikeItem());
	public static final RegistryObject<Item> IRONPIKE = REGISTRY.register("ironpike", () -> new IronpikeItem());
	public static final RegistryObject<Item> GOLDPIKE = REGISTRY.register("goldpike", () -> new GoldpikeItem());
	public static final RegistryObject<Item> DIAMONDPIKE = REGISTRY.register("diamondpike", () -> new DiamondPikeItem());
	public static final RegistryObject<Item> NETHERITEPIKE = REGISTRY.register("netheritepike", () -> new NetheritePikeItem());
	public static final RegistryObject<Item> STONEHALBERD = REGISTRY.register("stonehalberd", () -> new StonehalberdItem());
	public static final RegistryObject<Item> IRONHALBERD = REGISTRY.register("ironhalberd", () -> new IronhalberdItem());
	public static final RegistryObject<Item> GOLDHALBERD = REGISTRY.register("goldhalberd", () -> new GoldhalberdItem());
	public static final RegistryObject<Item> DIAMONDHALBERD = REGISTRY.register("diamondhalberd", () -> new DiamondhalberdItem());
	public static final RegistryObject<Item> NETHERITEHALBERD = REGISTRY.register("netheritehalberd", () -> new NetheritehalberdItem());
	public static final RegistryObject<Item> CUIRASS_CHESTPLATE = REGISTRY.register("cuirass_chestplate", () -> new CuirassItem.Chestplate());
	public static final RegistryObject<Item> PERCUSSIONCAPGUNKIT = REGISTRY.register("percussioncapgunkit", () -> new PercussioncapgunkitItem());
	public static final RegistryObject<Item> PERCUSSIONCAP_BLUEPRINT = REGISTRY.register("percussioncap_blueprint", () -> new PercussioncapBlueprintItem());
	public static final RegistryObject<Item> FULMINATEPOWDER = REGISTRY.register("fulminatepowder", () -> new FulminatepowderItem());
	public static final RegistryObject<Item> PERCUSSIONNIPPLE = REGISTRY.register("percussionnipple", () -> new PercussionnippleItem());
	public static final RegistryObject<Item> FLINTLOCK_MECHANISM = REGISTRY.register("flintlock_mechanism", () -> new FlintlockMechanismItem());
	public static final RegistryObject<Item> PERCUSSIONCAP_MECHANISM = REGISTRY.register("percussioncap_mechanism", () -> new PercussioncapMechanismItem());
	public static final RegistryObject<Item> MINIE_BALL = REGISTRY.register("minie_ball", () -> new MinieBallItem());
	public static final RegistryObject<Item> MINIE_PAPER_CARTIDGE_AMMO = REGISTRY.register("minie_paper_cartidge_ammo", () -> new MiniePaperCartidgeAmmoItem());
	public static final RegistryObject<Item> BROWNING_HARMONICA_CLIP = REGISTRY.register("browning_harmonica_clip", () -> new BrowningHarmonicaClipItem());
	public static final RegistryObject<Item> HEAVY_MUSKETBALL = REGISTRY.register("heavy_musketball", () -> new HeavyMusketballItem());
	public static final RegistryObject<Item> BIGBOREBARREL = REGISTRY.register("bigborebarrel", () -> new BigborebarrelItem());
	public static final RegistryObject<Item> CRUDE_BIGBOREBARREL = REGISTRY.register("crude_bigborebarrel", () -> new CrudeBigborebarrelItem());
	public static final RegistryObject<Item> SHOTGUN_SHELL = REGISTRY.register("shotgun_shell", () -> new ShotgunShellItem());
	public static final RegistryObject<Item> ADVANCED_REVOLVERS_BLUEPRINT = REGISTRY.register("advanced_revolvers_blueprint", () -> new AdvancedRevolversBlueprintItem());
	public static final RegistryObject<Item> DOUBLE_BARRELS_PART = REGISTRY.register("double_barrels_part", () -> new DoubleBarrelsPartItem());
	public static final RegistryObject<Item> RESEARCH_TABLE = block(GunsmithCognitisModBlocks.RESEARCH_TABLE);
	public static final RegistryObject<Item> FLINTLOCK_BLUEPRINT_INTERMEDIATE = REGISTRY.register("flintlock_blueprint_intermediate", () -> new FlintlockBlueprintIntermediateItem());
	public static final RegistryObject<Item> FLINTLOCK_BLUEPRINT_MASTERY = REGISTRY.register("flintlock_blueprint_mastery", () -> new FlintlockBlueprintMasteryItem());
	public static final RegistryObject<Item> PERCUSSIONCAP_BLUEPRINT_INTERMEDIATE = REGISTRY.register("percussioncap_blueprint_intermediate", () -> new PercussioncapBlueprintIntermediateItem());
	public static final RegistryObject<Item> PERCUSSIONCAP_BLUEPRINT_MASTERY = REGISTRY.register("percussioncap_blueprint_mastery", () -> new PercussioncapBlueprintMasteryItem());
	public static final RegistryObject<Item> MATCHLOCK_BLUEPRINT = REGISTRY.register("matchlock_blueprint", () -> new MatchlockBlueprintItem());
	public static final RegistryObject<Item> MATCHLOCK_BLUEPRINT_INTERMEDIATE = REGISTRY.register("matchlock_blueprint_intermediate", () -> new MatchlockBlueprintIntermediateItem());
	public static final RegistryObject<Item> MATCHLOCK_BLUEPRINT_MASTERY = REGISTRY.register("matchlock_blueprint_mastery", () -> new MatchlockBlueprintMasteryItem());
	public static final RegistryObject<Item> WHEELLOCK_BLUEPRINT = REGISTRY.register("wheellock_blueprint", () -> new WheellockBlueprintItem());
	public static final RegistryObject<Item> WHEELLOCK_BLUEPRINT_INTERMEDIATE = REGISTRY.register("wheellock_blueprint_intermediate", () -> new WheellockBlueprintIntermediateItem());
	public static final RegistryObject<Item> WHEELLOCK_BLUEPRINT_MASTERY = REGISTRY.register("wheellock_blueprint_mastery", () -> new WheellockBlueprintMasteryItem());
	public static final RegistryObject<Item> UNIVERSAL_BLUEPRINT = REGISTRY.register("universal_blueprint", () -> new UniversalBlueprintItem());
	public static final RegistryObject<Item> BOLT_MECHANISM = REGISTRY.register("bolt_mechanism", () -> new BoltMechanismItem());
	public static final RegistryObject<Item> CHASSEPOT_BAYONET = REGISTRY.register("chassepot_bayonet", () -> new ChassepotBayonetItem());
	public static final RegistryObject<Item> MATCHLOCK_ARQUEBUS = REGISTRY.register("matchlock_arquebus", () -> new MatchlockArquebusItem());
	public static final RegistryObject<Item> HANDGUNNE = REGISTRY.register("handgunne", () -> new HandgunneItem());
	public static final RegistryObject<Item> THREEEYEGUN = REGISTRY.register("threeeyegun", () -> new ThreeeyegunItem());
	public static final RegistryObject<Item> MATCHLOCK_BLUNDERBUSS = REGISTRY.register("matchlock_blunderbuss", () -> new MatchlockBlunderbussItem());
	public static final RegistryObject<Item> FLINTLOCKMUSKET = REGISTRY.register("flintlockmusket", () -> new FlintlockmusketItem());
	public static final RegistryObject<Item> FLINTLOCKMUSKETBAYONET = REGISTRY.register("flintlockmusketbayonet", () -> new FlintlockmusketbayonetItem());
	public static final RegistryObject<Item> FLINTLOCKMUSKETGOLD = REGISTRY.register("flintlockmusketgold", () -> new FlintlockmusketgoldItem());
	public static final RegistryObject<Item> FLINTLOCK_PISTOL = REGISTRY.register("flintlock_pistol", () -> new FlintlockPistolItem());
	public static final RegistryObject<Item> FLINTLOCK_PISTOL_GOLD = REGISTRY.register("flintlock_pistol_gold", () -> new FlintlockPistolGoldItem());
	public static final RegistryObject<Item> WHEELLOCK_PISTOL = REGISTRY.register("wheellock_pistol", () -> new WheellockPistolItem());
	public static final RegistryObject<Item> WHEELLOCK_MUSKET = REGISTRY.register("wheellock_musket", () -> new WheellockMusketItem());
	public static final RegistryObject<Item> FLINTLOCK_DOUBLE_BARREL_MUSKET = REGISTRY.register("flintlock_double_barrel_musket", () -> new FlintlockDoubleBarrelMusketItem());
	public static final RegistryObject<Item> FLINTLOCK_PEPPERBOX = REGISTRY.register("flintlock_pepperbox", () -> new FlintlockPepperboxItem());
	public static final RegistryObject<Item> TANEGASHIMA = REGISTRY.register("tanegashima", () -> new TanegashimaItem());
	public static final RegistryObject<Item> MATCHLOCK_SNAPHANCE_MUSKET = REGISTRY.register("matchlock_snaphance_musket", () -> new MatchlockSnaphanceMusketItem());
	public static final RegistryObject<Item> JEZAILMUSKET = REGISTRY.register("jezailmusket", () -> new JezailmusketItem());
	public static final RegistryObject<Item> MATCHLOCK_AXE_PISTOL = REGISTRY.register("matchlock_axe_pistol", () -> new MatchlockAxePistolItem());
	public static final RegistryObject<Item> MATCHLOCK_WALL_GUN = REGISTRY.register("matchlock_wall_gun", () -> new MatchlockWallGunItem());
	public static final RegistryObject<Item> WHEELLOCK_CARBINE = REGISTRY.register("wheellock_carbine", () -> new WheellockCarbineItem());
	public static final RegistryObject<Item> WHEELLOCK_SPORTING_RIFLE = REGISTRY.register("wheellock_sporting_rifle", () -> new WheellockSportingRifleItem());
	public static final RegistryObject<Item> FLINTLOCK_RIFLED_CARBINE = REGISTRY.register("flintlock_rifled_carbine", () -> new FlintlockRifledCarbineItem());
	public static final RegistryObject<Item> FLINTLOCK_ASUMETTE_RIFLED_WALL_GUN = REGISTRY.register("flintlock_asumette_rifled_wall_gun", () -> new FlintlockAsumetteRifledWallGunItem());
	public static final RegistryObject<Item> FLINTLOCK_DOUBLE_BARREL_PISTOL = REGISTRY.register("flintlock_double_barrel_pistol", () -> new FlintlockDoubleBarrelPistolItem());
	public static final RegistryObject<Item> FLINTLOCK_LORENZONI_REPEATER = REGISTRY.register("flintlock_lorenzoni_repeater", () -> new FlintlockLorenzoniRepeaterItem());
	public static final RegistryObject<Item> FLINTLOCK_PEPPERBOX_CARBINE = REGISTRY.register("flintlock_pepperbox_carbine", () -> new FlintlockPepperboxCarbineItem());
	public static final RegistryObject<Item> WHEELLOCK_KALTHOFF_REPEATER = REGISTRY.register("wheellock_kalthoff_repeater", () -> new WheellockKalthoffRepeaterItem());
	public static final RegistryObject<Item> DIVINE_FIVE_THUNDER_MACHINE = REGISTRY.register("divine_five_thunder_machine", () -> new DivineFiveThunderMachineItem());
	public static final RegistryObject<Item> FLINTLOCK_HEAVY_DRAGOON_PISTOL = REGISTRY.register("flintlock_heavy_dragoon_pistol", () -> new FlintlockHeavyDragoonPistolItem());
	public static final RegistryObject<Item> NOCK_VOLLEY_GUN = REGISTRY.register("nock_volley_gun", () -> new NockVolleyGunItem());
	public static final RegistryObject<Item> FERGUSON_RIFLE = REGISTRY.register("ferguson_rifle", () -> new FergusonRifleItem());
	public static final RegistryObject<Item> FLINTLOCK_HAND_MORTAR = REGISTRY.register("flintlock_hand_mortar", () -> new FlintlockHandMortarItem());
	public static final RegistryObject<Item> ROCK = REGISTRY.register("rock", () -> new RockItem());
	public static final RegistryObject<Item> FLINTLOCK_COLLIER_REVOLVER = REGISTRY.register("flintlock_collier_revolver", () -> new FlintlockCollierRevolverItem());
	public static final RegistryObject<Item> FLINTLOCK_COLLIER_REVOLVING_CARBINE = REGISTRY.register("flintlock_collier_revolving_carbine", () -> new FlintlockCollierRevolvingCarbineItem());
	public static final RegistryObject<Item> DYNAMITE = REGISTRY.register("dynamite", () -> new DynamiteItem());
	public static final RegistryObject<Item> DYNAMITE_PACK = REGISTRY.register("dynamite_pack", () -> new DynamitePackItem());
	public static final RegistryObject<Item> PATTERN_1851MINIERIFLE = REGISTRY.register("pattern_1851minierifle", () -> new Pattern1851minierifleItem());
	public static final RegistryObject<Item> LORENZ_PISTOL = REGISTRY.register("lorenz_pistol", () -> new LorenzPistolItem());
	public static final RegistryObject<Item> KENTUCKY_PISTOL = REGISTRY.register("kentucky_pistol", () -> new KentuckyPistolItem());
	public static final RegistryObject<Item> BROWNING_HARMONICA_RIFLE = REGISTRY.register("browning_harmonica_rifle", () -> new BrowningHarmonicaRifleItem());
	public static final RegistryObject<Item> HANDCANNON = REGISTRY.register("handcannon", () -> new HandcannonItem());
	public static final RegistryObject<Item> MIQUOLET_MUSKET = REGISTRY.register("miquolet_musket", () -> new MiquoletMusketItem());
	public static final RegistryObject<Item> WHEELLOCK_PETRONEL = REGISTRY.register("wheellock_petronel", () -> new WheellockPetronelItem());
	public static final RegistryObject<Item> FLINTLOCK_BLUNDERBUSS = REGISTRY.register("flintlock_blunderbuss", () -> new FlintlockBlunderbussItem());
	public static final RegistryObject<Item> MATCHLOCK_HEAVY_ARQUEBUS = REGISTRY.register("matchlock_heavy_arquebus", () -> new MatchlockHeavyArquebusItem());
	public static final RegistryObject<Item> LANDSKNECHT_HARKEBUS = REGISTRY.register("landsknecht_harkebus", () -> new LandsknechtHarkebusItem());
	public static final RegistryObject<Item> MATCHLOCK_PISTOL = REGISTRY.register("matchlock_pistol", () -> new MatchlockPistolItem());
	public static final RegistryObject<Item> DREYSE_NEEDLE_GUN = REGISTRY.register("dreyse_needle_gun", () -> new DreyseNeedleGunItem());
	public static final RegistryObject<Item> DOUBLE_BARREL_SHOTGUN = REGISTRY.register("double_barrel_shotgun", () -> new DoubleBarrelShotgunItem());
	public static final RegistryObject<Item> PATTERN_1851_MINIE_RIFLE_BAYONET = REGISTRY.register("pattern_1851_minie_rifle_bayonet", () -> new Pattern1851MinieRifleBayonetItem());
	public static final RegistryObject<Item> SAWN_OFF_DOUBLE_BARREL_SHOTGUN = REGISTRY.register("sawn_off_double_barrel_shotgun", () -> new SawnOffDoubleBarrelShotgunItem());
	public static final RegistryObject<Item> COLT_PETERSON_1836 = REGISTRY.register("colt_peterson_1836", () -> new ColtPeterson1836Item());
	public static final RegistryObject<Item> COLT_DRAGOON_1848 = REGISTRY.register("colt_dragoon_1848", () -> new ColtDragoon1848Item());
	public static final RegistryObject<Item> COLT_WALKER_1847 = REGISTRY.register("colt_walker_1847", () -> new ColtWalker1847Item());
	public static final RegistryObject<Item> COLT_REVOLVING_RIFLE_1855 = REGISTRY.register("colt_revolving_rifle_1855", () -> new ColtRevolvingRifle1855Item());
	public static final RegistryObject<Item> COLT_ARMY_1860 = REGISTRY.register("colt_army_1860", () -> new ColtArmy1860Item());
	public static final RegistryObject<Item> SPRINGFIELD_MODEL_1861_RIFLED_MUSKET = REGISTRY.register("springfield_model_1861_rifled_musket", () -> new SpringfieldModel1861RifledMusketItem());
	public static final RegistryObject<Item> SPRINGFIELD_MODEL_1861_RIFLED_MUSKET_BAYONET = REGISTRY.register("springfield_model_1861_rifled_musket_bayonet", () -> new SpringfieldModel1861RifledMusketBayonetItem());
	public static final RegistryObject<Item> FUSIL_1866_CHASSEPOT = REGISTRY.register("fusil_1866_chassepot", () -> new Fusil1866ChassepotItem());
	public static final RegistryObject<Item> FUSIL_1866_CHASSEPOT_BAYONET = REGISTRY.register("fusil_1866_chassepot_bayonet", () -> new Fusil1866ChassepotBayonetItem());
	public static final RegistryObject<Item> JOSEPH_EGG_PISTOL = REGISTRY.register("joseph_egg_pistol", () -> new JosephEggPistolItem());
	public static final RegistryObject<Item> BIG_GAME_4_BORE_PERCUSSION_RIFLE = REGISTRY.register("big_game_4_bore_percussion_rifle", () -> new BigGame4BorePercussionRifleItem());
	public static final RegistryObject<Item> HAND_BOMB = REGISTRY.register("hand_bomb", () -> new HandBombItem());
	public static final RegistryObject<Item> ADAMS_1856_REVOLVER = REGISTRY.register("adams_1856_revolver", () -> new Adams1856RevolverItem());
	public static final RegistryObject<Item> ENFIELD_1853_MUSKET_RIFLE = REGISTRY.register("enfield_1853_musket_rifle", () -> new Enfield1853MusketRifleItem());
	public static final RegistryObject<Item> SAWN_OFF_COLT_REVOLVER_1855 = REGISTRY.register("sawn_off_colt_revolver_1855", () -> new SawnOffColtRevolver1855Item());
	public static final RegistryObject<Item> PORTER_TURRET_RIFLE = REGISTRY.register("porter_turret_rifle", () -> new PorterTurretRifleItem());
	public static final RegistryObject<Item> COLT_REVOLVING_SHOTGUN_1855 = REGISTRY.register("colt_revolving_shotgun_1855", () -> new ColtRevolvingShotgun1855Item());
	public static final RegistryObject<Item> SAWN_COLT_REVOLVING_SHOTGUN_1855 = REGISTRY.register("sawn_colt_revolving_shotgun_1855", () -> new SawnColtRevolvingShotgun1855Item());
	public static final RegistryObject<Item> HEAVY_MUSKET_BALL_PROJECTILE = REGISTRY.register("heavy_musket_ball_projectile", () -> new HeavyMusketBallProjectileItem());

	// Start of user code block custom items
	// End of user code block custom items
	private static RegistryObject<Item> block(RegistryObject<Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties()));
	}
}
